# Generated by Django 4.1.7 on 2023-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termauthors',
            name='termauthor',
            field=models.TextField(db_column='termAuthor', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termauthors',
            name='termdate',
            field=models.TextField(db_column='termDate', default=1),
            preserve_default=False,
        ),
    ]
