# Generated by Django 4.1.7 on 2023-04-29 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnect', '0002_termauthors_termauthor_termauthors_termdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termauthors',
            name='termdate',
            field=models.DateTimeField(blank=True, db_column='termDate', default=datetime.datetime.now),
        ),
    ]
